[package]
name = "easy-async"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = { version = "*" }
parking = { version = "*" }
concurrent-queue = { version = "*" }
easy-parallel = { version = "*" }
slab = { version = "*" }


futures-timer = { version = "*" }

# monoio = { version = "*" }

smol = { version = "*" }
futures-lite = { version = "*" }
async-lock = { version = "*" }
async-task = { version = "*" }
async-executor = { version = "*" }
async-channel = { version = "*" }

crossbeam = { version = "*" }

futures-core = { version = "*" }


futures = { version = "*" }


tokio = { version = "*", features = ["full"] }
async-std = { version = "*", features = ["unstable", "attributes"] }
waker-fn = { version = "*" }
mini-redis = { version = "*" }
mini-tokio = { version = "*" }


# [target.'cfg(loom)'.dependencies]
# loom = { version = "0.7", optional = true }
