[package]
name = "easy-async"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
async-std = { version = "*", features = ["unstable"] }
waker-fn = { version = "*" }
crossbeam = { version = "*" }
futures-lite = { version = "*" }
futures = { version = "*" }
num_cpus = { version = "*" }
mini-redis = { version = "*" }
smol = { version = "*" }
futures-timer = { version = "*" }
mini-tokio = { version = "*" }
